shift/urls.py
from django.urls import path
from .import views

app_name='shift'

urlpatterns=[
    #掲示板・意見箱
    path('OB',views.ListOBView.as_view(),name='OB'),
    path('OB/board_edit/<int:pk>/',views.UpdateViewBoradView.as_view(),name='board-edit'),
    path('OB/board_detail/<int:pk>/',views.DetailBoardView.as_view(),name='board-detail'),
    path('OB/opinion_create/',views.CreateOpinionView.as_view(),name='opinion-create'),
    path('OB/opinion_list/',views.ListOpinionView.as_view(),name='opinion-list'),
    #店舗選択
    path('staff_create',views.CreateStaffView.as_view(),name='store-info'),
    # メッセージ送信(送信先選択)
    path('send/',views.send,name='send'),
    path('select_destination/<slug:user_id>/', views.get_destination_info, name='select'),
    # メッセージ送信(メッセージ履歴)
    path('history/<slug:dest_id>/', views.get_message_history, name='history'),
    path('update_history/', views.ajax_update_history, name='update_history'),

    #シフト編集
    path('edit/',views.edit,name='edit'),
    path('addShift/',views.add_shift,name='add_shift'),
    path('listShift/',views.get_shift,name='get_shift'),
    #シフト閲覧(従業員)
    path('confirm/',views.confirm,name='confirm'),
    path('confirmShift/',views.confirm_shift,name='confirm_shift'),
    #シフト閲覧(雇用者)
    path('confirm_author/',views.confirm_author,name='confirm_author'),
    path('confirmShiftAuthor/',views.confirm_shift_author,name='confirm_shift_author'),
    path('ShiftOthers/',views.shift_others,name='shift_others'),
    #給料計算
    path('ShiftMine/',views.shift_mine,name='shift_mine'),
    #シフト承認
    path('authorize/',views.authorize,name='authorize'),
    path('authorize_detail/', views.authorize_detail, name='authorize_detail'),
    path('authorizeShift/<int:id>', views.authorizeShift, name='authorizeShift'),
    #シフト削除
    path('delete/',views.delete,name='delete'),
    path('delete_detail/', views.delete_detail, name='delete_detail'),
    path('deleteShift/<int:id>', views.deleteShift, name='deleteShift'),
]

shiftproject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
urlpatterns = [
    path('index',views.index_view,name='index'),
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('shift/',include('shift.urls')),
]

shift/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
# Create your models here.
class Staff(models.Model):
    user=models.OneToOneField('accounts.User',verbose_name='スタッフ',on_delete=models.CASCADE)
    store=models.ForeignKey('Store',verbose_name='店舗',on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.store}:{self.user}'


class Store(models.Model):
    name=models.CharField('店舗',max_length=20)
    wage=models.IntegerField('時給')
    
    def __str__(self):
        return self.name

class Message(models.Model):
    indivisual_id = models.PositiveIntegerField()
    dest_id = models.PositiveIntegerField()
    message = models.CharField(max_length=2000)
    read_status = models.PositiveIntegerField()
    send_time = models.DateTimeField(auto_now_add=True)

    # 未読数のリストを返す
    def calc_unread_number_list(self,indivisual_id,dest_id_list):
        success_flag = 1
        unread_number_list = []

        for dest_id in dest_id_list:
            unread_number = 0
            unread_number = Message.objects.filter(
                indivisual_id = dest_id,
                dest_id = indivisual_id,
                read_status = 0
            ).count()
            unread_number_list.append(unread_number)

        return success_flag,unread_number_list

    # 個人IDと送信先のIDに対応したメッセージ履歴を返す
    def get_message_history(self,indivisual_id,dest_id):
        success_flag = 1

        # 相手から送られたメッセージに既読をつける
        dest_message = Message.objects.filter(
            Q(indivisual_id = dest_id, dest_id = indivisual_id)
        )
        for message in dest_message:
            message.read_status = 1
            message.save(force_update=True)
        
        # メッセージ履歴を取得
        message_history = Message.objects.filter(
            Q(indivisual_id = indivisual_id,dest_id = dest_id) 
            | Q(indivisual_id = dest_id, dest_id = indivisual_id)
        )
        return success_flag,message_history
    
    # 新規メッセージが送られているかどうかと自分のメッセージの未読数を返す
    def update_message_history(self,indivisual_id,dest_id):
        detect_flag = False

        # 送信先の未読数を取得
        dest_unread_number = Message.objects.filter(
            indivisual_id = dest_id,
            dest_id = indivisual_id,
            read_status = 0
        ).count()

        # 自分の未読数を取得
        my_unread_number = Message.objects.filter(
            indivisual_id = indivisual_id,
            dest_id = dest_id,
            read_status = 0
        ).count()

        # 送信先の未読数が0でなければTrue
        if not dest_unread_number == 0:
            detect_flag = True
        return detect_flag,my_unread_number

class Board(models.Model):
    store=models.OneToOneField('Store',verbose_name='店舗',on_delete=models.CASCADE)
    text=models.TextField()


class Opinion(models.Model):
    store=models.ForeignKey('Store',verbose_name='店舗',on_delete=models.CASCADE)
    text=models.TextField()

class ShiftData(models.Model):
    user_id=models.CharField(max_length=100)
    date=models.DateField()
    start_time=models.IntegerField()
    end_time=models.IntegerField()
    confirmed_flag=models.IntegerField()
    store_id=models.CharField(max_length=20)

shift/forms.py
from .models import Staff, Message
from django import forms


class StaffCreateForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ('store',)


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["message"]


class CalendarForm(forms.Form):

    start_date = forms.IntegerField(required=True)
    end_date = forms.IntegerField(required=True)


class ShiftForm(forms.Form):

    date = forms.IntegerField(required=True)
    time = forms.CharField(required=True, max_length=10)


class ConfirmForm(forms.Form):
    date = forms.IntegerField(required=True)

shift/views.py
from calendar import isleap
from django.shortcuts import redirect, render
from accounts.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from shift.forms import StaffCreateForm, MessageForm
from .models import Message, Board, Opinion, Store, Staff, ShiftData
from django.views.generic import(
    View,
    ListView,
    CreateView,
    UpdateView,
    DetailView,
)
from django.http import Http404, HttpResponse, JsonResponse, HttpResponseRedirect
import time #給料計算
import json
from .forms import CalendarForm, ShiftForm, ConfirmForm
from django.middleware.csrf import get_token
from django.template import loader
from django.urls import reverse
from django.template.loader import render_to_string # ajax_update_history

# Create your views here.

'''
モジュール名: get_destination_list
作成者: 國枝直希
日付: 2022.7.10
機能要約: 各個人IDに対応するメッセージの送信先のID, 名前のリストを返す
'''

def get_destination_list(user_id):
    # 自分の所属する店舗IDを取得
    shop_id = Staff.objects.filter(user=user_id).values('store')[0]['store']

    # 同じ店舗IDに所属するユーザーを取得
    dest_id_list = Staff.objects.filter(store=shop_id).values('user')

    # 送信先のid, 名前のリストを作成
    dest_list = []
    dest_name_list = []
    for dest_id in dest_id_list:
        dest = dest_id['user']
        dest_name = User.objects.filter(
            id=dest_id['user']
        ).values_list('username', flat=True)[0]
        dest_list.append(dest)
        dest_name_list.append(dest_name)
    
    # 送信先のリストから自分自身を除外
    dest_list.pop(dest_list.index(user_id.id))
    dest_name_list.pop(dest_name_list.index(user_id.username))
    return dest_list, dest_name_list

'''
モジュール名: get_destination_info
作成者: 國枝直希
日付: 2022.7.10
機能要約: 各個人IDに対応するメッセージの送信先選択画面をレンダリングする
'''

def get_destination_info(request, user_id):
    user_id = request.user

    # 送信先のリスト, 未読数を取得
    dest_list, dest_name_list = get_destination_list(user_id)
    flag, unread_list = Message().calc_unread_number_list(user_id.id, dest_list)

    # テンプレートに送信先の名前と未読数をまとめて渡す準備
    dest_zip = zip(dest_name_list, unread_list)
    if not flag:
        return render(
            request,
            'shift/select_destination.html',
            {'dest_list': dest_zip}
        )
    return render(
        request,
        'shift/select_destination.html',
        {'dest_list': dest_zip}
    )

'''
モジュール名: send
作成者: 國枝直希
日付: 2022.7.10
機能要約: 送信先選択画面へ遷移する
'''

def send(request):
    return redirect("shift:select", user_id=request.user)

'''
モジュール名: ajax_update_history
作成者: 國枝直希
日付: 2022.7.10
機能要約: メッセージが送信先から送られたどうかと未読数, 最新のメッセージ履歴をJson形式で返す
'''

def ajax_update_history(request):
    ind_ID = request.user.id

    # GET リクエストの取得
    dest_name = request.GET['dest_name']

    # Ajax側に返す情報を取得
    dest_ID = User.objects.filter(username=dest_name).values_list('id',flat=True)[0]
    detect_flag, unread_number = Message().update_message_history(ind_ID,dest_ID)
    flag,messages = Message().get_message_history(ind_ID,dest_ID)
    context = {'messages':messages,'user_id':request.user,'dest_name':dest_name}

    # 最新のメッセージ履歴をテンプレートを使ってレンダリング
    content = render_to_string("shift/content.html",context,request)
    if detect_flag:
        # 相手からの新規メッセージがあった場合
        data = {'flag':True,'unread_number':unread_number,'content':content}
    else:
        # 相手からの新規メッセージがなかった場合
        data = {'flag':False,'unread_number':unread_number,'content':content}
    return JsonResponse(data)

'''
モジュール名: get_message_history
作成者: 國枝直希
日付: 2022.7.10
機能要約: 各個人IDに対応する選択された送信先とのメッセージ履歴をレンダリングし, 
         メッセージを送信した場合は内容をメッセージ履歴DBに保存する
'''

def get_message_history(request, dest_id):
    ind_ID = request.user.id
    dest_ID = User.objects.filter(username=dest_id).values_list('id', flat=True)[0]
    dest_name = dest_id

    # メッセージ履歴を取得
    messages = Message()
    flag, messages = messages.get_message_history(ind_ID, dest_ID)

    # POST の場合: メッセージ送信
    if request.method == "POST":
        message_info = Message(
            indivisual_id=ind_ID,
            dest_id=dest_ID,
            read_status=0
        )
        # request.POST: message内容のみ
        # メッセージ履歴に保存できるようformにインスタンスを提供
        form = MessageForm(request.POST, instance=message_info)
        if form.is_valid():
            message = form.save(commit=False)
            message.post = messages
            message.save()
            return redirect("shift:history", dest_id=dest_id)
    else:
        # GET の場合は空のフォームを作成
        form = MessageForm()

    if not flag:
        return render(
            request,
            'shift/history.html',
            {'messages': messages, 'form': form,
            'user_id': request.user, 'dest_name': dest_name}
        )
    return render(
        request,
        'shift/history.html',
        {'messages': messages, 'form': form,
        'user_id': request.user, 'dest_name': dest_name}
    )

'''
モジュール名:  ListOBView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗ごとの掲示板送信・確認ページや意見送信・意見箱ページを表示
'''
class ListOBView(LoginRequiredMixin, ListView):
    model = Board
    template_name = 'shift/board_list.html'
# 今ログインいているユーザーが所属している店舗に関するページを表示
    def get_queryset(self):
        store = Staff.objects.get(user=self.request.user)
        store_id = store.store
        queryset = super().get_queryset()
        return queryset.filter(store=store_id)

'''
モジュール名:  UPdateViewBoradView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗ごとの掲示板内容を更新する
'''
class UpdateViewBoradView(LoginRequiredMixin, UpdateView):
    model = Board
    fields = (['text'])
    template_name = 'shift/board_edit.html'
    success_url = reverse_lazy('shift:OB')

'''
モジュール名:  DetailBoardView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗ごとの掲示板内容を表示する
'''
class DetailBoardView(LoginRequiredMixin, DetailView):
    model = Board
    fields = (['text'])
    template_name = 'shift/board_detail.html'

'''
モジュール名:  CreateOpinionView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗ごとの意見箱内容を更新する
'''

class CreateOpinionView(LoginRequiredMixin, CreateView):
    model = Opinion
    fields = (['text'])
    template_name = 'shift/opinion_create.html'
    success_url = reverse_lazy('shift:opinion-create')
    #現在ログインしているユーザーのIDをformに入れる 
    def form_valid(self, form):
        store = Staff.objects.get(user=self.request.user)
        store_id = store.store
        form.instance.store = store_id
        return super().form_valid(form)
'''
モジュール名:  ListOpinionView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗ごとの意見箱内容を表示する
'''
class ListOpinionView(LoginRequiredMixin, ListView):
    model = Opinion
    template_name = 'shift/opinion_list.html'
    success_url = reverse_lazy('shift:opinion-list')

    def get_queryset(self):
        store = Staff.objects.get(user=self.request.user)
        store_id = store.store
        queryset = super().get_queryset()
        return queryset.filter(store=store_id)

'''
モジュール名:  CreateStaffView
作成者:  叶恒志
日付:  2022.7.10
機能要約:  店舗とユーザーを紐づける
'''

class CreateStaffView(LoginRequiredMixin, CreateView):
    model = Staff
    form = StaffCreateForm
    fields = (['store'])
    template_name = 'shift/store_create.html'
    success_url = reverse_lazy('index')
    #すでに店舗を登録しているユーザーにはメニュー画面を表示させる
    def get_template_names(self):
        if Staff.objects.filter(user=self.request.user).exists():
            template_name='index.html'
        else:
            template_name='shift/store_create.html'

        return [template_name]

    #現在ログインしているユーザーのIDをformに入れる
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



'''
モジュール名: edit
作成者: 若田佳菜子
日付: 2022.7.11
機能要約: カレンダーを表示する
'''
def edit(request):
    shift = ShiftData.objects.filter(user_id=request.user.id)
    get_token(request)
    #template = loader.get_template('shift/edit.html') #カレンダーを表示する
    #return HttpResponse(template.render())
    return render(request, 'shift/edit.html', {'shift_list':shift},)

'''
モジュール名: add_shift
作成者: 若田佳菜子
日付: 2022.7.11
機能要約: データベースにシフトの登録を行う
'''
def add_shift(request):
    if request.method == "GET":
        # GETは対応しない
        raise Http404()

    # JSONの解析
    datas = json.loads(request.body)

    # バリデーション
    shiftForm = ShiftForm(datas)
    if shiftForm.is_valid() == False:
        # バリデーションエラー
        raise Http404()

    # リクエストの取得
    Date = datas["date"]
    Time = datas["time"]

    # 日付に変換。JavaScriptのタイムスタンプはミリ秒なので秒に変換
    formatted_date = time.strftime(
        "%Y-%m-%d", time.localtime(Date / 1000))
    splitedTime = Time.split('-')
    start_time = int(splitedTime[0])
    end_time = int(splitedTime[1])
    store = Staff.objects.get(user=request.user,)

    # 登録処理
    shift = ShiftData(
        user_id=request.user,
        date=formatted_date,
        start_time=start_time,
        end_time=end_time,
        confirmed_flag=0,
        store_id=store.store,
    )
    shift.save()

    # 空を返却
    return HttpResponse("edit")

'''
モジュール名: get_shift
作成者: 若田佳菜子
日付: 2022.7.11
機能要約: カレンダーに表示するイベントをデータベースから取得する
'''
def get_shift(request):
    if request.method == "GET":
        # GETは対応しない
        raise Http404()

    # JSONの解析
    datas = json.loads(request.body)

    # バリデーション
    calendarForm = CalendarForm(datas)
    if calendarForm.is_valid() == False:
        # バリデーションエラー
        raise Http404()

    # リクエストの取得
    start_date = datas["start_date"]
    end_date = datas["end_date"]
    # 日付に変換。JavaScriptのタイムスタンプはミリ秒なので秒に変換
    formatted_start_date = time.strftime(
        "%Y-%m-%d", time.localtime(start_date / 1000))
    formatted_end_date = time.strftime(
        "%Y-%m-%d", time.localtime(end_date / 1000))

    # FullCalendarの表示範囲のみ表示

shift/templates/shift/authorize.html
{% extends 'base.html' %}

{% block title %}シフト承認{% endblock %}
{% block h1 %}シフト承認{% endblock %}
{% block content %}
<div class="container">
  <form action="{% url 'shift:authorize_detail' %}" method="post">
    {% csrf_token %}
    <div class="info">
      <div class="input-message">日付を入力してください</div>
      <input type="date" name="date_field" required="required" class="shift-calendar">
      <input type="submit" value="Search" class="search-btn">
    </div>
  </form>


  <br>
  {% if shift_list %}
  <table border="1">
    {% for shift in shift_list %}
    <tr class="shift-table">
      <td>{{ shift.user_id }}</td>
      <td>{{ shift.date }}</td>
      <td>{{ shift.start_time }}</td>
      <td>{{ shift.end_time }}</td>
      <td><button onclick="location.href='{% url 'shift:authorizeShift' shift.id %}'">承認</button></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <h2>{{ authorize_text }}<h2>
      {% endif %}
</div>

<style>
  .input-message {
    font-size: 35px;
    text-decoration: underline;
    text-decoration-color: yellow;
    text-decoration-thickness: 5px;
  }

  .info {
    display: flex;
    margin: 20px 0 0 20px;
    padding: auto 0;
    border-bottom: 4px solid;
  }

  .container {
    border: 5px solid;
    width: 70%;
    height: 500px;
    margin: 0 auto;
    border-radius: 10px;
  }

  .shift-table {
    width: 100%;

  }

  table {
    width: 90%;
    font-size: 45px;
    margin: 20px auto 0 auto;
  }

  td {
    text-align: center;

  }

  tr {
    margin-bottom: 20px;
  }


  .shift-calendar {
    font-size: 50px;
    margin-left: 20px;
    border: 2px solid;
    margin-bottom: 10px;
  }

  .search-btn {
    font-size: 30px;
    height: 50px;
    margin-top: 10px;
    margin-left: 30px;
    border-radius: 10px;
    box-shadow: 3px 3px 3px black;
  }

  .search-btn:hover {
    background-color: rgba(10, 202, 245, 0.7);
  }

  button {
    margin: 10px 0;
    font-size: 30px;
    border-radius: 10px;
    border: 2px solid;
  }

  button:hover {
    background-color: rgb(255, 110, 20);
  }
</style>
{% endblock content %}

shift/templates/shift/board_detail.html
{% extends 'base.html' %}

{% block title %}掲示板{% endblock %}
{% block content %}
<div class="board">
    <span class="title"><i class="fa-solid fa-circle-small"></i>掲示板</span>
    <div class="board-detail">
        {{object.text}}
    </div>
</div>

<style>
    i {
        color: black;
    }

    .board {
        display: block;
        border: 20px solid rgb(248, 112, 0);
        background-color: rgba(228, 144, 18, 0.4);
        box-shadow: 8px 8px 1px black;
        height: 500px;
        width: 70%;
        margin: 0 auto;
        /* background-image: url(https://thumb.ac-illust.com/86/8648dc63957c50e6b02a842c65e7d677_t.jpeg); */
        background-size: cover;

    }

    .board .title {
        text-align: center;
        position: absolute;
        top: 25%;
        left: 50%;
        padding: 5px 25px;
        background-color: #ee4719;
        border-radius: 4px;
        color: #fff;
        font-size: 40px;
        transform: translate(-50%, -50%);
    }

    .board .title ::before {
        font-family: "Font Awesome 5 Free";
        content: "\f111";
        font-size: 30px;
        color: #fff;
        margin-right: 5px;
    }


    .board-detail {
        padding-top: 200px;
        text-align: center;
        font-size: 40px;
        font-family: "Meiryo";
        text-decoration: underline;
        font-weight: bold;
    }
</style>
{% endblock content %}

shift/templates/shift/board_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}掲示板編集{% endblock %}
{% block h1 %}掲示板編集{% endblock %}
{% block content %}
<div>
    <form method='POST'>{% csrf_token %}
        {{ form.text|add_class:'form-board'}}
        <button type='submit'>確定</button>
    </form>
</div>

<style>
    .form-board {
        font-size: 30px;
        width: 70%;
        margin-left: 15%;
        border: 2px solid;
        border-radius: 5px;
        display: block;
        border: 20px solid rgb(248, 112, 0);
        background-color: rgba(228, 144, 18, 0.4);
        box-shadow: 8px 8px 1px black;
        height: 500px;
        width: 70%;
        margin: 0 auto;
        /* background-image: url(https://thumb.ac-illust.com/86/8648dc63957c50e6b02a842c65e7d677_t.jpeg); */
        background-size: cover;

    }

    button {
        position: absolute;
        display: block;
        width: 150px;
        height: 70px;
        font-size: 45px;
        left: 50%;
        bottom: 20%;
        transform: translate(-50%, -50%);
        background: linear-gradient(135deg, #ffd900, #ff9300);
        color: white;
        font-weight: bold;
        border-radius: 8px;
        transition: 0.3s;
        border: 2px solid #ff9300;
        background: #fff;
        color: #ff9300;
    }

    button:hover {
        background: #ff9300;
        color: #fff;
    }
</style>
{% endblock content %}

shift/templates/shift/board_list.html
{% extends 'base.html' %}

{% block title %}意見箱・掲示板{% endblock %}
{% block h1 %}掲示板{% endblock %}
{% block content %}
<div class="outer_container">
    <div class="inner_container">
        {% for item in object_list %}
        {% if request.user.is_staff %}
        <a href="{% url 'shift:board-edit' item.pk %}" class="btn board-edit">掲示板編集
            <p class="exp">掲示板の編集を行う事ができます。</p>
        </a>
        {% else %}
        <a href="{% url 'shift:board-detail' item.pk%}" class="btn board-confirm">掲示板確認
            <p class="exp">店舗からの連絡を確認することができます。</p>
        </a>
        {% endif %}
        {% endfor %}
        {% if request.user.is_staff %}
        <a href="{% url 'shift:opinion-list' %}" class="btn opinion-box">意見箱
            <p class="exp">従業員から届いた意見を一覧で確認することができます。</p>
        </a>
        {% else %}
        <a href="{% url 'shift:opinion-create' %}" class="btn opinion-send">意見送信
            <p class="exp">雇用者に匿名で意見を送信することができます。</p>
        </a>
        {% endif %}
    </div>
</div>

<style>
    .outer_container {}

    .inner_container {
        display: flex;
        justify-content: center;
    }

    .btn {
        background-color: #1F6FD8;
        padding: 30px 20px;
        margin: 10px 30px;
        font-size: 30px;
        color: white;
        font-weight: bold;
        opacity: 0.8;
        border-radius: 20px;
        width: 40%;
        text-align: center;
        box-shadow: 5px 5px 5px black;
    }


    .btn:hover {
        opacity: 1.0;
        box-shadow: none;
        transform: translateY(5px);
    }

    .exp {
        color: rgb(0, 0, 0);
        font-size: 20px;
        z-index: 2;
        text-decoration: underline black;
        text-decoration-thickness: 4px;
        font-weight: normal;
    }
</style>
{% endblock content %}

shift/templates/shift/content.html
{% if messages %}
{% for message in messages %}
{% if message.indivisual_id == user_id.id %}
<!-- css適用するとき用 -->
<!-- 自分の吹き出し -->
<div class="message__right">
    <div class="message-right-name">{{user_id.username}}</div>
    <div class="message-right-text">{{message.message}}</div>
    <div class="message-right-date">
        {% if message.read_status == 1 %}
        <p style="text-align:right" class="date">既読 {{message.send_time}}</p>
        {% else %}
        <p style="text-align:right" class="date">{{message.send_time}}</p>
        {% endif %}
    </div>
</div>

{% else %}
<!-- css適用するとき用 -->
<!-- 相手の吹き出し -->
<div class="message__left">
    <div class="message-left-name">{{dest_name}}</div>
    <div class="message-left-text">{{message.message}}</div>
    <span class="message-left-date">{{message.send_time}}</span>
</div>
{% endif %}
{% endfor %}
{% endif %}

shift/templates/shift/delete.html
{% extends 'base.html' %}

{% block title %}シフト削除{% endblock %}
{% block h1 %}シフト削除{% endblock %}
{% block content %}

<div class="container">
  <form action="{% url 'shift:delete_detail' %}" method="post">
    <div class="info">
      {% csrf_token %}
      <input type="date" name="date_field" required="required" class="shift-calendar">
      <input type="submit" value="Search" class="search-btn">
    </div>
  </form>

  <br>

  {% if shift_list %}
  <table border="1">
    {% for shift in shift_list %}
    <tr class="shift-table">
      <td>{{ shift.date }}</td>
      <td>{{ shift.start_time }}</td>
      <td>{{ shift.end_time }}</td>
      <td>{{ shift.confirmed_flag }}</td>
      <td>
        <form method="post" action="{% url 'shift:deleteShift' shift.id %}">{% csrf_token %}
          <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <h2 class="delete_text">{{ delete_text }}</h2>
  {% endif %}

  <a href="{% url 'shift:edit' %}" class="back-to-edit">編集画面へ戻る
    <i class="fa-solid fa-angles-left"></i></a>
</div>

<style>
  .input-message {
    font-size: 35px;
    text-decoration: underline;
    text-decoration-color: yellow;
    text-decoration-thickness: 5px;
  }

  .info {
    display: flex;
    margin: 20px 30% 0 30%;
    padding: auto 0;
    border-bottom: 4px solid;

  }

  .container {
    border: 5px solid;
    width: 70%;
    height: 500px;
    margin: 0 auto;
    border-radius: 10px;
  }

  .shift-table {
    width: 100%;

  }

  table {
    width: 90%;
    font-size: 45px;
    margin: 20px auto 0 auto;
  }

  td {
    text-align: center;

  }

  tr {
    margin-bottom: 20px;
  }


  form {}

  .shift-calendar {
    font-size: 50px;
    margin-left: 20px;
    border: 2px solid;
    margin-bottom: 10px;
    color: rgb(255, 110, 20);
  }



  .search-btn {
    font-size: 30px;
    height: 50px;
    margin-top: 10px;
    margin-left: 30px;
    border-radius: 10px;
    box-shadow: 3px 3px 3px black;
  }

  .search-btn:hover {
    background-color: rgba(10, 202, 245, 0.7);
  }

  button {
    margin: 10px 0;
    font-size: 30px;
    border-radius: 10px;
    border: 2px solid;
  }

  button:hover {
    background-color: rgb(255, 20, 20);
  }

  .delete_text {
    text-align: center;
  }


  .back-to-edit {
    display: block;
    margin: 100px auto 0 auto;
    border: 3px solid rgb(44, 224, 21);
    border-radius: 10px;
    width: 400px;
    height: 50px;
    text-align: center;
    padding: 10px 0;
    font-size: 30px;
    background-color: rgba(9, 176, 59, 0.5);
    font-weight: bold;
    box-shadow: 5px 5px 5px black;
    color: rgb(0, 0, 0);
  }

  .back-to-edit:hover {
    background-color: rgba(9, 176, 59, 1.0);
    box-shadow: none;
  }

  .back-to-edit:active {
    border-color: white;
    color: white;
  }
</style>
{% endblock content %}