accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView

from .views import SignupView

app_name='accounts'
urlpatterns=[
    path('',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',SignupView.as_view(),name='signup'),
]

shift/urls.py
from django.urls import path
from .import views

app_name='shift'

urlpatterns=[
    #掲示板・意見箱
    path('OB',views.ListOBView.as_view(),name='OB'),
    path('OB/board_edit/<int:pk>/',views.UpdateViewBoradView.as_view(),name='board-edit'),
    path('OB/board_detail/<int:pk>/',views.DetailBoardView.as_view(),name='board-detail'),
    path('OB/opinion_create/',views.CreateOpinionView.as_view(),name='opinion-create'),
    path('OB/opinion_list/',views.ListOpinionView.as_view(),name='opinion-list'),
    #店舗選択
    path('staff_create',views.CreateStaffView.as_view(),name='store-info'),
    # メッセージ送信(送信先選択)
    path('send/',views.send,name='send'),
    path('select_destination/<slug:user_id>/', views.get_destination_info, name='select'),
    # メッセージ送信(メッセージ履歴)
    path('history/<slug:dest_id>/', views.get_message_history, name='history'),
    path('update_history/', views.ajax_update_history, name='update_history'),

    #シフト編集
    path('edit/',views.edit,name='edit'),
    path('addShift/',views.add_shift,name='add_shift'),
    path('listShift/',views.get_shift,name='get_shift'),
    #シフト閲覧(従業員)
    path('confirm/',views.confirm,name='confirm'),
    path('confirmShift/',views.confirm_shift,name='confirm_shift'),
    #シフト閲覧(雇用者)
    path('confirm_author/',views.confirm_author,name='confirm_author'),
    path('confirmShiftAuthor/',views.confirm_shift_author,name='confirm_shift_author'),
    path('ShiftOthers/',views.shift_others,name='shift_others'),
    #給料計算
    path('ShiftMine/',views.shift_mine,name='shift_mine'),
    #シフト承認
    path('authorize/',views.authorize,name='authorize'),
    path('authorize_detail/', views.authorize_detail, name='authorize_detail'),
    path('authorizeShift/<int:id>', views.authorizeShift, name='authorizeShift'),
    #シフト削除
    path('delete/',views.delete,name='delete'),
    path('delete_detail/', views.delete_detail, name='delete_detail'),
    path('deleteShift/<int:id>', views.deleteShift, name='deleteShift'),
]

shiftproject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
urlpatterns = [
    path('index',views.index_view,name='index'),
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('shift/',include('shift.urls')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}|シフトアプリ</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
    <script src="https://kit.fontawesome.com/5a63c6cd21.js" crossorigin="anonymous"></script>
</head>

<body>
    <link rel="stylesheet" href="{% static 'shift/css/style.css' %}">
    <nav class="base">
        {% if request.user.is_authenticated %}
        <a href="{% url 'index' %}" class="base-back">メニュー</a>
        <div class="Welcome-message">ようこそ、{{request.user.username}}さん！</div>
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="base-logout">ログアウト</a>
        {% else %}
        <a href="{% url 'accounts:login' %}" class="base-login">ログイン</a>
        <a href="{% url 'accounts:signup' %}" class="base-register">会員登録</a>
        <div class="guest-message">ようこそ、ゲストさん！</div>
        {% endif %}
    </nav>
    <div>
        <h1><span class="high-light">{% block h1 %}{% endblock %}</span></h1>
        {% block content %}{% endblock content %}
    </div>
</body>
<style>
    h1 {
        text-align: center;
        font-size: 60px;
    }

    .high-light {
        background: linear-gradient(transparent 50%, #ffff66 0%);
        line-height: 1.3em;
    }



    body {
        margin: 0;
        font-family: "Helvetica Neue";
        /* font-family: "Hiragino Kaku Gothic ProN";  */
        background-color: #ffffff;
        background-size: cover;

    }

    .base {
        background-color: rgb(203, 203, 218);
        height: 70px;
        width: auto;
        padding: 30px 20px 10px 20px;
        border-bottom: 3px solid black;
    }



    .base a {
        color: black;
        font-weight: bold;
        font-size: 35px;
        margin: 0 20px;
        width: 100px;
        height: 100px;
        background-color: rgba(94, 94, 253, 0.3);
        border-radius: 10px;
    }

    .base-back,
    .base-login,
    .base-logout,
    .base-register {
        width: auto;
        background-color: azure;
        padding: 10px 20px;
    }

    .base-back:hover,
    .base-login:hover,
    .base-logout:hover,
    .base-register:hover {
        background-color: rgba(94, 94, 253, 0.8);
        box-shadow: none;
        transform: translateY(10px);
    }

    .Welcome-message {
        position: absolute;
        right: 20px;
        text-align: center;
        display: inline;
        font-size: 35px;
        font-weight: bold;
    }

    .guest-message {
        position: absolute;
        right: 20px;
        text-align: center;
        display: inline;
        font-size: 35px;
        font-weight: bold;
    }
</style>



</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}メニュー{% endblock %}
{% block h1 %}メニュー{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
{% else %}
<div class="if_guest">ログインまたは会員登録<i class="fa-solid fa-angles-up"></i></div>
{% endif %}
<div class="container">
    <div class="upper_container">
        {% if request.user.is_staff %}
        <a href="{% url 'shift:confirm_author' %}" class="btn confirm_author">シフト閲覧
            <p class="exp">各従業員から提出されたシフトを確認することができます。</p>
        </a>
        <a href="{% url 'shift:authorize' %}" class="btn authorize">シフト承認
            <p class="exp">各従業員から提出されたシフトの承認をすることができます。</p>
        </a>
        {% else %}
        <a href=" {% url 'shift:edit' %}" class="btn editing">シフト編集<i class="fa-solid fa-file"></i>
            <p class="exp">シフトの編集を行うことができます。</p>
        </a>
        <a href="{% url 'shift:confirm' %}" class="btn confirm">シフト閲覧<i class="fa-solid fa-display"></i>
            <p class="exp">承認されたシフトの閲覧を行うことができます。</p>
        </a>
        {% endif %}
    </div>
    <div class="lower_container">
        <a href="{% url 'shift:send' %}" class="btn message_send">メッセージ送信<i class="fa-solid fa-message"></i>
            <p class="exp">同じ店舗で働く従業員・雇用者へ<br>メッセージを送ることができます。</p>
        </a>
        <a href="{% url 'shift:OB' %}" class="btn board">掲示板・意見箱<i class="fa-solid fa-chalkboard-user"></i>
            {% if request.user.is_staff %}
            <p class="exp">掲示板の編集や、意見箱の確認を行うことができます。</p>
            {% else %}
            <p class="exp">店舗からの連絡の確認や、意見箱への投稿を行うことができます。</p>
            {% endif %}
        </a>
    </div>
</div>
<style>
    .if_guest {
        position: absolute;
        font-size: 30px;
        margin-top: -10%;
        margin-left: 10px;
        color: red;
        font-weight: bold;
        border: 4px solid red;
        width: 25%;
        background-color: white;
    }

    .fa-angles-up {
        margin-left: 20px;
    }

    .container {
        justify-content: center;
    }

    .upper_container {
        display: flex;
        /* margin-top: 7%; */
        justify-content: center;
    }

    .lower_container {
        display: flex;
        justify-content: center;
    }

    .btn {
        background-color: #1F6FD8;
        padding: 30px 20px;
        margin: 10px 30px;
        font-size: 30px;
        color: white;
        font-weight: bold;
        opacity: 0.8;
        border-radius: 20px;
        width: 40%;
        text-align: center;
        box-shadow: 5px 5px 5px black;
    }

    .btn i {
        margin-left: 20px;
        color: white;
        font-size: 40px;
        z-index: 2;
    }

    .exp {
        color: rgb(0, 0, 0);
        font-size: 20px;
        z-index: 2;
        text-decoration: underline black;
        text-decoration-thickness: 4px;
        font-weight: normal;
    }

    .btn:hover {
        opacity: 1.0;
        box-shadow: none;
        transform: translateY(5px);
    }
</style>
{% endblock content %}